#
# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.
#
# ICGC Storage Client - Default Configuration
#

###############################################################################
# Profile - common
###############################################################################

client:
  ansi: ${ansi:true}
  silent: ${silent:false}
  quiet: ${quiet:false}
  accessToken: "${accessToken}" # Alias for backwards compatibility
  connectTimeoutSeconds: 60
  readTimeoutSeconds: 60
    
  ssl:
    custom: false

transport:
  fileFrom: memory
  memory: 1
  parallel: 6

storage:
  url: http://localhost:5431
  retryNumber: 10
  retryTimeout: 1	

metadata:
  url: https://meta.icgc.org
  ssl:
    enabled: true
    
portal:
  url: https://dcc.icgc.org  
    
logging:
  file: target/logs/client.log
  
mount:
  logging: false

---

###############################################################################
# Profile - "aws"
###############################################################################

spring.profiles: aws

storage:
  url: https://virginia.cloud.icgc.org

client:
  ssl:
    custom: false
    
---

###############################################################################
# Profile - "collab"
###############################################################################

spring.profiles: collab

# Storage server
storage:
  url: https://storage.cancercollaboratory.org

client:    
  ssl:
    custom: false  

---

###############################################################################
# Profile - "oicr"
###############################################################################

spring.profiles: oicr

# uses storage.url and client.ssl.custom define in common 


---

###############################################################################
# Profile - "debug"
###############################################################################

spring.profiles: debug

logging:
  level:
    org.icgc.dcc.storage: DEBUG
    springframework.retry: DEBUG
    springframework.web: DEBUG
    com.amazonaws.services: DEBUG
